apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
 name: datagrid-operator
 namespace: example-datagrid-instance
spec:
 channel: 8.2.x
 installPlanApproval: Automatic
# installPlanApproval: Manual
 name: datagrid
 source: redhat-operators
 sourceNamespace: openshift-marketplace
# startingCSV: datagrid-operator.v8.2.0
